### ISSUE TITLE
Test is broken

### ISSUE THREAD

**Issue by rainingmaster** [openresty/test-nginx#102]
@agentzh @doujiang24  Hi, I found the test for test-nginx is broken, and the ci is failed: https://travis-ci.org/github/openresty/test-nginx/jobs/705896738

Also, [other project's test case which rely on this tool is also failed too](https://travis-ci.org/github/openresty/lua-upstream-nginx-module/jobs/706375438#L811)

If I use the command `--notest` in cpanm, [it will install success and run success](https://github.com/openresty/lua-upstream-nginx-module/pull/72)

**Comment by xiaocang** [comment]
It was found that the module dependency declaration for testing was missing from Makefile.PL, and I committed PR here:
https://github.com/openresty/test-nginx/pull/103
cc @agentzh
