### ISSUE TITLE
Bad value in the env TEST_NGINX_WORKER_USER: www-data

### ISSUE THREAD

**Issue by Limsanity** [openresty/test-nginx#148]
[this line of code](https://github.com/openresty/test-nginx/blob/1120efdc88656ed8c204150567bd5d2af2283361/lib/Test/Nginx/Util.pm#L111) won't allow to set TEST_NGINX_WORKER_USER to www-data, could you please explain the reason, thanks.

**Comment by zhuizhuhaomeng** [comment]
fixed, please update to the lastest master code.

**Comment by Limsanity** [comment]
It works, thanks
