### ISSUE TITLE
[question] upload file request support?!

### ISSUE THREAD

**Issue by rryqszq4** [openresty/test-nginx#30]
hi @agentzh
How to use Test::Nginx post upload file test. Like this:
```sh
curl -F "file=@b4.jpg" http://localhost/ -v
```

**Comment by agentzh** [comment]
@rryqszq4 You can check the test suite of lua-resty-upload for real-world examples.

**Comment by rryqszq4** [comment]
@agentzh It's done, thx.  ^.^
