### ISSUE TITLE
[Question] how to use output body as a param to check

### ISSUE THREAD

**Issue by detailyang** [openresty/test-nginx#36]
Hello, agentzh. :grin:
test-nginx is awesome:)
I'm writing a module which can generate QRcode image. i wish get the response body then decode this QRcode image to check whether is right.
can Test::Nginx::Socket put response body as param to check like follow:
# assume

``` perl
--- response_body eval
should.be.equal(self, '123')
```

**Comment by agentzh** [comment]
@detailyang It cannot do that yet. The `eval` filter you're using applies to your *expected output*, instead of the actual output. We need some mechanism to specify custom filters on the actual output data. How about this?

```
--- response_body_filters eval
\&my_decoder_function
--- response_body chomp
123
```

**Comment by detailyang** [comment]
@agentzh  LGTM. :grin:
wish we can use this feature as soon as fast :rocket: :rocket:

**Comment by agentzh** [comment]
@detailyang Patches welcome :)

**Comment by detailyang** [comment]
@agentzh 
yep,  let me try :grin: ..(i'm not familiar with perl)

**Comment by detailyang** [comment]
Hello @agentzh , I provide a PR #37 
It looks good to me and i have tested in this nginx module [nginx barcode module](https://github.com/detailyang/ngx_http_barcode).
But it's first time to write perl in real world :smile:, please help me review this PR if you can
