### ISSUE TITLE
[FR] Provide default http_config and default config

### ISSUE THREAD

**Issue by spacewander** [openresty/test-nginx#39]
In some occasions, we need to use the same `http_config` across tests in the same test file. Currently I have to copy `--- http_config eval: $::HttpConfig` and paste it every test to achieve this requirement.

IMHO, make a default `http_config` possible may be a good solution. For example, we can put a default `http_config` before the `=== Test 1`, and let all tests share it. For a test requires its own `http_config`, we just define its own one like what we need to do currently.

BTW, I am glad to see a default `config` too.

**Comment by agentzh** [comment]
@spacewander It's already supported. For example,

```
use Test::Nginx::Socket 'no_plan';

add_block_preprocessor(sub {
    my $block = shift;

    if (!defined $block->config) {
        $block->set_value("config", <<'_END_');
location = /t {
    echo $arg_a;
}
_END_
    }
});

run_tests();

__DATA__

=== TEST 1:
--- request
    GET /t?a=3
--- response_body
3



=== TEST 2:
--- request
    GET /t?a=blah
--- response_body
blah
```

This is per-file. You can also make it across all the `.t` files. Just create a subclass of `Test::Nginx::Socket`, as in,

```perl
package t::MyTester;

use Test::Nginx::Socket -Base;

add_block_preprocessor(sub {
    my $block = shift;

    if (!defined $block->config) {
        $block->set_value("config", <<'_END_');
location = /t {
    echo $arg_a;
}
_END_
    }
});

1;
```

Save this as file `t/MyTester.pm`. And then in one of your `.t` file:

```
use t::MyTester 'no_plan';

run_tests();

__DATA__

=== TEST 1:
--- request
    GET /t?a=3
--- response_body
3



=== TEST 2:
--- request
    GET /t?a=blah
--- response_body
blah
```

You can do the same with the `http_config` section, or even inventing your own new sections. This is very powerful.

**Comment by spacewander** [comment]
Thank you for your reply! 
Maybe you could write a section about extending testing DSL via perl in https://github.com/openresty/programming-openresty/tree/master/testing to teach those skills?

**Comment by agentzh** [comment]
@spacewander Yes, that's a good idea.
