### ISSUE TITLE
udp client/server support for Test::Nginx::Socket::Lua::Stream

### ISSUE THREAD

**Issue by alonbg** [openresty/test-nginx#40]
udp stream_server_config, stream_config, stream_request and stream response

**Comment by agentzh** [comment]
@alonbg I think we should add a `Test::Nginx::Socket::Lua::Datagram` test class here, which provides sections `dgram_server_config`, `dgram_config`, `dgram_request`, and `dgram_response` :) Its implementation should look very similar to `Test::Nginx::Socket::Lua::Stream`. Are you interested in contributing a patch for that? Many thanks!

**Comment by alonbg** [comment]
Done.
Didn't touch version numbers.
Please review pull request.

**Comment by alonbg** [comment]
pull request for this feature accepted and merged. closing
