### ISSUE TITLE
request_body_like with multiple requests

### ISSUE THREAD

**Issue by wcbastian** [openresty/test-nginx#45]
I am trying to get request_body_like to work with multiple requests and seem unable to, what am I missing?

See https://gist.github.com/wcbastian/059ab19baf7e9ee282fef62a27d3e3d6

The first 3 tests work fine, but test 4 errors out with "Bailout called.  Further testing stopped:  TEST 4: Multiple matching responses - You asked for many requests, the expected results should be arrays as well."

How should test 4 look like?

**Comment by agentzh** [comment]
@wcbastian I'm afraid `--- response_body_like` does not yet support array values. It looks like a bug. Patches welcome :)

**Comment by wcbastian** [comment]
I actually think I just got it too work with this:
```
--- response_body_like eval
[ qr/^OK [0-9]*$/, qr/^OK [0-9]*$/ ]

```

**Comment by wcbastian** [comment]
Mystery solved. Thanks @agentzh for all your work on OpenResty, it's really nice.

**Comment by agentzh** [comment]
@wcbastian Glad you figured it out and happy you like OpenResty :)
