### ISSUE TITLE
Warning in Util.pm:581

### ISSUE THREAD

**Issue by salazar** [openresty/test-nginx#61]
Hey,

I'm getting this while running all of my test cases: "WARNING: killing the child process 22 with force... at /usr/local/share/perl5/site_perl/Test/Nginx/Util.pm line 581". Wouldn't it make sense to put it inside an 'if verbose', as with other warn statements?

Cheers!

**Comment by agentzh** [comment]
@salazar It's by design since I believe this warning is important enough to be always shown.
