### ISSUE TITLE
[question] can run multiple nginx instance with different port at the same time?

### ISSUE THREAD

**Issue by detailyang** [openresty/test-nginx#64]
My scene is testing multiple nginx instance with different IDC. I wish running test-nginx to test multiple nginx instance with differenct port.

Cannot found anything from [Test::Nginx::Socket](https://metacpan.org/pod/Test::Nginx::Socket). May I missing something ? Not sure this feature is need or create a PR to implement ?

**Comment by agentzh** [comment]
@detailyang See https://metacpan.org/pod/Test::Nginx::Socket#TEST_NGINX_PORT

**Comment by agentzh** [comment]
Though I'm not really sure what exactly are you trying to do.

**Comment by detailyang** [comment]
thanks. I will get close to look at this :)
