### ISSUE TITLE
"load_module" directive is specified too late.

### ISSUE THREAD

**Issue by gnought** [openresty/test-nginx#69]
Define TEST_NGINX_LOAD_MODULES environmental variable will cause an error when testing `stream-lua-nginx-module/t/002-content.t`

The excerpt of generated nginx.conf is as follows:

```
worker_processes  1;
daemon on;
master_process off;
error_log /build/ngxc/t/servroot/logs/error.log debug;
pid       /build/ngxc/t/servroot/logs/nginx.pid;
env MOCKEAGAIN_VERBOSE;
env MOCKEAGAIN;
env MOCKEAGAIN_WRITE_TIMEOUT_PATTERN;
env LD_PRELOAD;
env LD_LIBRARY_PATH;
env DYLD_INSERT_LIBRARIES;
env DYLD_FORCE_FLAT_NAMESPACE;
#env LUA_PATH;
#env LUA_CPATH;

stream {

    server {
        listen 1985;

    content_by_lua_block { ngx.say(nil) }

    }
}
load_module /build/ngxc/ngx/modules/ngx_http_headers_more_filter_module.so; 
http {
...
}
```

**Comment by agentzh** [comment]
@gnought Seems like the `load_module` directives should be inserted before the `stream {}` config block. Will you contribute a pull request to the test-nginx repo below?

https://github.com/openresty/test-nginx

Thanks!
