### ISSUE TITLE
Errors during installation -- Dependencies not installed

### ISSUE THREAD

**Issue by AlecHFerguson** [openresty/test-nginx#70]
I'm trying to install `Test::Nginx` in an Alpine Linux Docker container, but getting this error:

```
Building and testing HTML-Parser-3.72 ... ! Installing HTML::Entities failed. See /root/.cpanm/work/1511941822.6/build.log for details. Retry with --force to force install it.
FAIL
```

This is the only line that says "error":

```
cc -c   -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Os -fomit-fr
Parser.xs:17:20: fatal error: EXTERN.h: No such file or directory
 #include "EXTERN.h"                      
                    ^                                       
compilation terminated.                       
make: *** [Makefile:368: Parser.o] Error 1
```

Any idea why `EXTERN.h` would not be found? More generally, what packages are required to run Test::Nginx? Thanks!

**Comment by agentzh** [comment]
@AlecHFerguson You need the perl header files for compiling a perl C module. `EXTERN.h` is a perl header file. On Fedora, for example, it is shipped with the perl-devel RPM package.

**Comment by AlecHFerguson** [comment]
Thanks @agentzh , I'll try that this evening.

Consider adding a list of package dependencies in the installation section of the readme? Would be helpful for PERL newbs like me. I'm happy to create a PR as well.

**Comment by agentzh** [comment]
@AlecHFerguson I think that applies to all Perl modules with C dependencies. And I don't think we want to add that for every Perl module we create. That does not follow the Perl community's convention anyway.
